spring.application.name=finance-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/devops
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/devops/protocol/openid-connect/certs
