spring.application.name=finance-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/auth/realms/devops
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/devops/protocol/openid-connect/certs

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=finance

spring.flyway.default-schema=finance
spring.flyway.schemas=finance
spring.flyway.create-schemas=true
