spring.application.name=event-service

management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/auth/realms/devops
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/devops/protocol/openid-connect/certs

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=event

spring.flyway.default-schema=event
spring.flyway.schemas=event
spring.flyway.create-schemas=true
