/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organization/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all sports */
        get: operations["getAllSports"];
        put?: never;
        /** Create sport */
        post: operations["createSport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/sports/{sport_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sport */
        get: operations["getSport"];
        put?: never;
        post?: never;
        /** Delete sport */
        delete: operations["deleteSport"];
        options?: never;
        head?: never;
        /** Update sport */
        patch: operations["updateSport"];
        trace?: never;
    };
    "/organization/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all teams */
        get: operations["getAllTeams"];
        put?: never;
        /** Create team */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get team */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        /** Delete team */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        /** Update team */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all members */
        get: operations["getAllMembers"];
        put?: never;
        /** Create member */
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get member details */
        get: operations["getMemberDetails"];
        put?: never;
        post?: never;
        /** Delete member */
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        /** Update member details */
        patch: operations["updateMemberDetails"];
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all events */
        get: operations["getAllEvents"];
        put?: never;
        /** Create event */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get event details */
        get: operations["getEventDetails"];
        put?: never;
        post?: never;
        /** Delete event */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /** Update event details */
        patch: operations["updateEventDetails"];
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all feedback */
        get: operations["getAllFeedback"];
        put?: never;
        /** Create feedback */
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get feedback details */
        get: operations["getFeedbackDetails"];
        put?: never;
        post?: never;
        /** Delete feedback */
        delete: operations["deleteFeedback"];
        options?: never;
        head?: never;
        /** Update feedback details */
        patch: operations["updateFeedbackDetails"];
        trace?: never;
    };
    "/finance/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all balances */
        get: operations["getAllBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/balances/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get member balance */
        get: operations["getMemberBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all transactions */
        get: operations["getAllTransactions"];
        put?: never;
        /** Create transaction */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transaction */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /** Delete transaction */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /** Update transaction */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/letters/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send mail */
        post: operations["sendMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/letters/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get pdf */
        post: operations["getPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/report/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generate report */
        get: operations["generateReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            message: string;
        };
        BadRequestResponse: {
            message: string;
            errors?: components["schemas"]["ErrorResponse"][];
        };
        Sport: {
            name: string;
            description: string;
            created_at: string;
            directors: string[];
        };
        /** @description Data transfer object for creating a new Sport. */
        SportCreate: {
            name: string;
            description?: string;
            directors?: string[];
        };
        /** @description Data transfer object for partially updating an existing Sport (PATCH operation). */
        SportPartialUpdate: {
            name?: string;
            description?: string;
            directors?: string[];
        };
        Team: {
            id: string;
            name: string;
            description: string;
            created_at: string;
            address: string;
            sport: string;
            trainers: string[];
            trainees: string[];
        };
        /** @description Data transfer object for creating a new Team. */
        TeamCreate: {
            name: string;
            description?: string;
            address?: string;
            sport: string;
            trainers?: string[];
            trainees?: string[];
        };
        /** @description Data transfer object for partially updating an existing Team (PATCH operation). */
        TeamPartialUpdate: {
            name?: string;
            description?: string;
            address?: string;
            sport?: string;
            trainers?: string[];
            trainees?: string[];
        };
        Member: {
            id: string;
            first_name: string;
            last_name: string;
            email: string;
            birthday: string;
            phone_number: string;
            address: string;
            joining_date: string;
            information: string;
        };
        /** @description A simplified representation of a Member, typically used in list views. */
        MemberSummary: {
            id: string;
            first_name: string;
            last_name: string;
            email: string;
        };
        /** @description Data transfer object for partially updating an existing Member (PATCH operation). */
        MemberPartialUpdate: {
            first_name?: string;
            last_name?: string;
            email?: string;
            birthday?: string;
            phone_number?: string;
            address?: string;
            information?: string;
        };
        /** @description Data transfer object for creating a new Member. */
        MemberCreate: {
            first_name: string;
            last_name: string;
            email?: string;
            birthday?: string;
            phone_number?: string;
            address?: string;
            information?: string;
        };
        Event: {
            id: string;
            name: string;
            description: string;
            start_time: string;
            end_time: string;
            attendees?: string[];
            /** @description Names of the sports associated with this event. */
            sports_linked?: string[];
            /** @description IDs of the teams associated with this event. */
            teams_linked?: string[];
            creator: string;
        };
        /** @description A simplified representation of a Event, typically used in list views. */
        EventSummary: {
            id: string;
            name: string;
            start_time: string;
            end_time: string;
        };
        /** @description Data transfer object for partially updating an existing Event (PATCH operation). */
        EventPartialUpdate: {
            name?: string;
            description?: string;
            start_time?: string;
            end_time?: string;
            attendees?: string[];
            sports_linked?: string[];
            teams_linked?: string[];
        };
        /** @description Data transfer object for creating a new Event. */
        EventCreate: {
            name: string;
            description?: string;
            start_time: string;
            end_time: string;
            attendees?: string[];
            sports_linked?: string[];
            teams_linked?: string[];
        };
        Feedback: {
            id: string;
            event: string;
            member: string;
            creator: string;
            created_at: string;
            feedback: string;
        };
        /** @description A simplified representation of a Feedback, typically used in list views. */
        FeedbackSummary: {
            id: string;
            event: string;
            member: string;
            creator: string;
            created_at: string;
        };
        /** @description Data transfer object for partially updating an existing Feedback (PATCH operation). */
        FeedbackPartialUpdate: {
            event?: string;
            member?: string;
            feedback?: string;
        };
        /** @description Data transfer object for creating a new Feedback. */
        FeedbackCreate: {
            event: string;
            member: string;
            feedback: string;
        };
        /** @description A simplified representation of a Transaction, typically used in list views. */
        Transaction: {
            id: string;
            member: string;
            creator: string;
            amount_cents: number;
            created_at: string;
            title: string;
            description: string;
        };
        /** @description Data transfer object for partially updating an existing Transaction (PATCH operation). */
        TransactionPartialUpdate: {
            member?: string;
            amount_cents?: number;
            title?: string;
            description?: string;
        };
        /** @description Data transfer object for creating a new Transaction. */
        TransactionCreate: {
            member: string;
            amount_cents: number;
            title: string;
            description?: string;
        };
        Balance: {
            member: string;
            balance_cents: number;
        };
    };
    responses: {
        /** @description The server encountered an unexpected condition that prevented it from fulfilling the request. */
        InternalServerErrror: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server cannot find the requested resource. The endpoint may be invalid or the resource may no longer exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server could not understand the request due to invalid syntax. The client should modify the request and try again. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BadRequestResponse"];
            };
        };
        /** @description The request could not be completed due to a conflict with the current state of the resource. Resolve the conflict and try again. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request was successful, but there is no content to return in the response. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Authentication is required to access the requested resource. The client must include the appropriate credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server understood the request, but refuses to authorize it. Ensure the client has appropriate permissions. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        sport_name: string;
        team_id: string;
        member_id: string;
        event_id: string;
        feedback_id: string;
        transaction_id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllSports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    createSport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SportCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_name: components["parameters"]["sport_name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    deleteSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_name: components["parameters"]["sport_name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    updateSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_name: components["parameters"]["sport_name"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SportPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getAllTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getAllMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getMemberDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    updateMemberDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getAllEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getEventDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    updateEventDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getAllFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getFeedbackDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    deleteFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    updateFeedbackDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getAllBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getMemberBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getAllTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    sendMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/html": Record<string, never>;
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    getPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/html": Record<string, never>;
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
    generateReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerErrror"];
        };
    };
}
