/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organization/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all sports
         * @description Returns a list of all sports registered in the organization.
         *     - All authenticated users: can access this endpoint.
         *
         */
        get: operations["getAllSports"];
        put?: never;
        /**
         * Create sport
         * @description Creates a new sport in the organization.
         *     - Admins: can create sports.
         *
         */
        post: operations["createSport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/sports/{sport_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sport
         * @description Returns the details of a specific sport.
         *     - All authenticated users: can access this endpoint.
         *
         */
        get: operations["getSport"];
        put?: never;
        post?: never;
        /**
         * Delete sport
         * @description Deletes a sport from the organization.
         *     - Admins: can delete sports.
         *
         */
        delete: operations["deleteSport"];
        options?: never;
        head?: never;
        /**
         * Update sport
         * @description Partially updates an existing sport's details.
         *     - Directors: can update all fields except directors.
         *     - Admins: can update all fields.
         *
         */
        patch: operations["updateSport"];
        trace?: never;
    };
    "/organization/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all teams
         * @description Returns a list of all teams in the organization.
         *     - All authenticated users: can access this endpoint.
         *
         */
        get: operations["getAllTeams"];
        put?: never;
        /**
         * Create team
         * @description Creates a new team in the organization.
         *     - Directors: can create teams for their own sport.
         *     - Admins: can create teams for any sport.
         *
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get team
         * @description Returns the details of a specific team.
         *     - All authenticated users: can access this endpoint.
         *
         */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        /**
         * Delete team
         * @description Deletes a team from the organization.
         *     - Directors: can delete teams in their sport.
         *     - Admins: can delete any team.
         *
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        /**
         * Update team
         * @description Partially updates a team's details.
         *     - Trainers: can update all fields except sport and trainers.
         *     - Directors: can update all fields except sport.
         *     - Admins: can update all fields.
         *
         */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all members
         * @description Returns a list of all members in the organization.
         *     - All authenticated users: can access this endpoint.
         *
         */
        get: operations["getAllMembers"];
        put?: never;
        /**
         * Create member
         * @description Creates a new member in the organization. Includes a password field for setting initial credentials.
         *     - Admins: can create members.
         *
         */
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the caller's dashboard
         * @description Returns dashboard data tailored to the caller's highest role
         *     (admin > director > trainer > trainee). The `role` field discriminates the
         *     concrete shape of the response.
         *     - All authenticated users: can access their own dashboard.
         *
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get member details
         * @description Returns the full details of a specific member.
         *     - Members themselves: can view their own details.
         *     - Team members: can view details of others in the same team.
         *     - Trainers: can view details of members in their team.
         *     - Directors: can view details of members in their sport.
         *     - Admins: can view any member's details.
         *
         */
        get: operations["getMemberDetails"];
        put?: never;
        post?: never;
        /**
         * Delete member
         * @description Deletes a member from the organization.
         *     - Admins: can delete members.
         *
         */
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        /**
         * Update member details
         * @description Partially updates the details of a specific member.
         *     - Members themselves: can update their own details.
         *     - Admins: can update any member's details.
         *
         */
        patch: operations["updateMemberDetails"];
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all events
         * @description Returns a list of all events.
         *     - All authenticated users: can see events linked to their team or sport, or events where they are an attendee.
         *     - Creators: can see all events they created.
         *     - Admins: can see all events.
         *
         */
        get: operations["getAllEvents"];
        put?: never;
        /**
         * Create event
         * @description Creates a new event.
         *     - Directors: can create events for their sport.
         *     - Trainers: can create events for their team.
         *     - Admins: can create any event.
         *
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get event details
         * @description Returns the details of a specific event.
         *     - All authenticated users: can access events linked to their team or sport, or events where they are an attendee.
         *     - Creators: can view events they created.
         *     - Admins: can view any event.
         *
         */
        get: operations["getEventDetails"];
        put?: never;
        post?: never;
        /**
         * Delete event
         * @description Deletes a specific event.
         *     - Creators: can delete events they created.
         *     - Directors: can delete events linked to their sport.
         *     - Admins: can delete any event.
         *
         */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /**
         * Update event details
         * @description Partially updates the details of a specific event.
         *     - Creators: can update events they created.
         *     - Directors: can update events linked to their sport.
         *     - Admins: can update any event.
         *
         */
        patch: operations["updateEventDetails"];
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all feedback
         * @description Returns a list of all feedback entries.
         *     - Creators: can see feedback they submitted.
         *     - Members: can see feedback about themselves.
         *     - Admins: can see all feedback.
         *
         */
        get: operations["getAllFeedback"];
        put?: never;
        /**
         * Create feedback
         * @description Creates a new feedback entry for a member.
         *     - Trainers: can create feedback for their trainees.
         *     - Admins: can create feedback for any member.
         *
         */
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get feedback details
         * @description Returns the details of a specific feedback entry.
         *     - Creators: can view feedback they submitted.
         *     - Members: can view feedback about themselves.
         *     - Admins: can view any feedback.
         *
         */
        get: operations["getFeedbackDetails"];
        put?: never;
        post?: never;
        /**
         * Delete feedback
         * @description Deletes a specific feedback entry.
         *     - Creators: can delete feedback they submitted.
         *     - Admins: can delete any feedback.
         *
         */
        delete: operations["deleteFeedback"];
        options?: never;
        head?: never;
        /**
         * Update feedback details
         * @description Partially updates a specific feedback entry.
         *     - Creators: can update feedback they submitted.
         *     - Admins: can update any feedback.
         *
         */
        patch: operations["updateFeedbackDetails"];
        trace?: never;
    };
    "/finance/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all balances
         * @description Returns a list of all member balances.
         *     - Directors: can view balances of members in their sport.
         *     - Admins: can view all balances.
         *
         */
        get: operations["getAllBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/balances/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get member balance
         * @description Returns the balance of a specific member.
         *     - Members themselves: can view their own balance.
         *     - Directors: can view balances of members in their sport.
         *     - Admins: can view any member's balance.
         *
         */
        get: operations["getMemberBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all transactions
         * @description Returns a list of all transactions. Users only see transactions where they are the member or the creator.
         *     - Members: can see transactions they are part of.
         *     - Creators: can see transactions they created.
         *     - Directors: can see transactions for members in their sport.
         *     - Admins: can see all transactions.
         *
         */
        get: operations["getAllTransactions"];
        put?: never;
        /**
         * Create transaction
         * @description Creates a new financial transaction for a member.
         *     - Directors: can create transactions for members in their sport.
         *     - Admins: can create transactions for any member.
         *
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction
         * @description Returns the details of a specific transaction.
         *     - Members: can view transactions they are part of.
         *     - Creators: can view transactions they created.
         *     - Directors: can view transactions for members in their sport.
         *     - Admins: can view any transaction.
         *
         */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /**
         * Delete transaction
         * @description Deletes a specific transaction.
         *     - Creators: can delete transactions they created.
         *     - Admins: can delete any transaction.
         *
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /**
         * Update transaction
         * @description Partially updates a specific transaction. The member field can only be changed by admins.
         *     - Creators: can update transactions they created (except the member field).
         *     - Admins: can update any transaction including the member field.
         *
         */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/letters/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send mail
         * @description Sends a personalized mass email. The body carries a `subject` and an HTML `template`;
         *     placeholder tokens in both the subject and the template are replaced with each receiver's
         *     data, and one email is sent per receiver.
         *
         *     Receivers are determined from the caller's highest role:
         *     - **Admin**: all members.
         *     - **Director**: all directors, trainers, and trainees in their sport.
         *     - **Trainer**: all trainers and trainees of their team.
         *     - **Trainee / member-only**: forbidden — cannot use the letter service (`403`).
         *
         *     Assumes a director directs exactly one sport, a trainer trains exactly one team, and a
         *     trainee belongs to exactly one team.
         *
         *     Supported placeholder tokens (`{{snake_case}}`; an unknown or empty value resolves to an
         *     empty string):
         *     - Member: `{{first_name}}`, `{{last_name}}`, `{{full_name}}`, `{{email}}`, `{{address}}`,
         *       `{{phone_number}}`, `{{birthday}}`, `{{joining_date}}`.
         *     - Organization: `{{team_name}}`, `{{sport_name}}` — the receiver's team/sport, blank if none.
         *     - Finance: `{{balance}}` — the receiver's current balance, formatted (e.g. `€12.50`).
         *
         */
        post: operations["sendMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/letters/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get pdf
         * @description Generates a personalized mass-letter PDF. The body carries an HTML `template` whose
         *     placeholder tokens are replaced with each receiver's data. One letter is rendered per
         *     receiver — a layout block with the recipient's name and address followed by the
         *     token-substituted template — and all letters are concatenated into a single PDF.
         *
         *     Receivers are determined from the caller's highest role:
         *     - **Admin**: all members.
         *     - **Director**: all directors, trainers, and trainees in their sport.
         *     - **Trainer**: all trainers and trainees of their team.
         *     - **Trainee / member-only**: forbidden — cannot use the letter service (`403`).
         *
         *     Assumes a director directs exactly one sport, a trainer trains exactly one team, and a
         *     trainee belongs to exactly one team.
         *
         *     Supported placeholder tokens (`{{snake_case}}`; an unknown or empty value resolves to an
         *     empty string):
         *     - Member: `{{first_name}}`, `{{last_name}}`, `{{full_name}}`, `{{email}}`, `{{address}}`,
         *       `{{phone_number}}`, `{{birthday}}`, `{{joining_date}}`.
         *     - Organization: `{{team_name}}`, `{{sport_name}}` — the receiver's team/sport, blank if none.
         *     - Finance: `{{balance}}` — the receiver's current balance, formatted (e.g. `€12.50`).
         *
         */
        post: operations["getPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/reports/member/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List member reports
         * @description Lists the stored report summaries (without text) for a member, newest first.
         *     - The member themselves: can list their own reports.
         *     - Admin: can list reports for any member.
         *
         */
        get: operations["listMemberReports"];
        put?: never;
        /**
         * Generate member report
         * @description Kicks off asynchronous generation of an AI report for a member. Returns immediately; the
         *     finished report is persisted and can later be fetched via the report endpoints.
         *     - The member themselves: can generate their own report.
         *     - Admin: can generate a report for any member.
         *
         */
        post: operations["generateMemberReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/reports/team/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List team reports
         * @description Lists the stored report summaries (without text) for a team, newest first.
         *     - Trainers of the team: can list the team's reports.
         *     - Admin: can list reports for any team.
         *
         */
        get: operations["listTeamReports"];
        put?: never;
        /**
         * Generate team report
         * @description Kicks off asynchronous generation of an AI report for a team. Returns immediately; the
         *     finished report is persisted and can later be fetched via the report endpoints.
         *     - Trainers of the team: can generate the team's report.
         *     - Admin: can generate a report for any team.
         *
         */
        post: operations["generateTeamReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get report
         * @description Returns a single stored report including its full text. Works for both member and team
         *     reports; the `kind` field indicates which, and the matching reference is populated.
         *     - Member reports: the member themselves or an admin.
         *     - Team reports: a trainer of the team or an admin.
         *
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        /**
         * Delete report
         * @description Deletes a single stored report (member or team).
         *     - Member reports: the member themselves or an admin.
         *     - Team reports: a trainer of the team or an admin.
         *
         */
        delete: operations["deleteReport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/rag-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate RAG response
         * @description Answers a question using retrieval-augmented generation over the helper's PDF knowledge
         *     base. The optional `uselocal` flag switches the chat model for this request: `true` forces
         *     the local Ollama model, `false` forces OpenAI. When omitted, the service's configured
         *     default provider is used.
         *
         */
        post: operations["generateRagResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            message: string;
        };
        BadRequestResponse: {
            message: string;
            errors?: components["schemas"]["ErrorResponse"][];
        };
        /** @description A lightweight reference to another entity — its id plus a display name. */
        Reference: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @description Summary of a stored member report, without its generated text. */
        MemberReportSummary: {
            /** Format: uuid */
            id: string;
            member: components["schemas"]["Reference"];
            /** Format: date-time */
            created_at: string;
        };
        /** @description Summary of a stored team report, without its generated text. */
        TeamReportSummary: {
            /** Format: uuid */
            id: string;
            team: components["schemas"]["Reference"];
            /** Format: date-time */
            created_at: string;
        };
        /** @description A stored report including its generated text. `kind` indicates whether it is a member or
         *     team report; the matching `member`/`team` reference is populated accordingly.
         *      */
        Report: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "member" | "team";
            member?: components["schemas"]["Reference"];
            team?: components["schemas"]["Reference"];
            /** Format: date-time */
            created_at: string;
            text: string;
        };
        /** @description Role-specific dashboard payload. The `role` property discriminates which concrete
         *     shape is returned, following the caller's highest role (admin > director > trainer > trainee).
         *      */
        Dashboard: components["schemas"]["AdminDashboard"] | components["schemas"]["DirectorDashboard"] | components["schemas"]["TrainerDashboard"] | components["schemas"]["TraineeDashboard"];
        /** @description Club-wide aggregates shown to administrators. */
        AdminDashboard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "admin";
            total_members: number;
            total_sports: number;
            total_teams: number;
            total_directors: number;
            total_trainers: number;
            total_balance_cents: number;
            events_this_week: number;
        };
        /** @description Aggregates for the sport a director manages. */
        DirectorDashboard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "director";
            sport: components["schemas"]["Reference"];
            total_teams: number;
            total_members: number;
            sport_balance_cents: number;
            upcoming_events: number;
            teams: components["schemas"]["TeamBalanceSummary"][];
        };
        /** @description Per-team rollup of trainee count and aggregate balance. */
        TeamBalanceSummary: {
            team: components["schemas"]["Reference"];
            member_count: number;
            balance_cents: number;
        };
        /** @description Aggregates for the team a trainer manages, including feedback they authored. */
        TrainerDashboard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "trainer";
            team: components["schemas"]["Reference"];
            total_members: number;
            upcoming_events: number;
            recent_feedback: components["schemas"]["FeedbackSummary"][];
        };
        /** @description Personal aggregates shown to a trainee/member. */
        TraineeDashboard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "trainee";
            balance_cents: number;
            next_event: components["schemas"]["EventSummary"] | null;
            upcoming_events: number;
            recent_feedback: components["schemas"]["FeedbackSummary"][];
            recent_reports: components["schemas"]["MemberReportSummary"][];
        };
        /** @description The object representation of a Sport within the organization. */
        Sport: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date */
            created_at: string;
            directors: components["schemas"]["Reference"][];
        };
        /** @description Data transfer object for creating a new Sport. */
        SportCreate: {
            name: string;
            description?: string;
            directors?: string[];
        };
        /** @description Data transfer object for partially updating an existing Sport (PATCH operation). */
        SportPartialUpdate: {
            name?: string;
            description?: string;
            directors?: string[];
        };
        /** @description The object representation of a Team that belongs to a specific Sport. */
        Team: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date */
            created_at: string;
            address: string;
            sport: components["schemas"]["Reference"];
            trainers: components["schemas"]["Reference"][];
            trainees: components["schemas"]["Reference"][];
        };
        /** @description Data transfer object for creating a new Team. */
        TeamCreate: {
            name: string;
            description?: string;
            address?: string;
            /**
             * Format: uuid
             * @description ID of the sport this team belongs to.
             */
            sport: string;
            trainers?: string[];
            trainees?: string[];
        };
        /** @description Data transfer object for partially updating an existing Team (PATCH operation). */
        TeamPartialUpdate: {
            name?: string;
            description?: string;
            address?: string;
            /**
             * Format: uuid
             * @description ID of the sport this team belongs to.
             */
            sport?: string;
            trainers?: string[];
            trainees?: string[];
        };
        /** @description The object representation of a Member. All users are represented as a member. */
        Member: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            email: string;
            /** Format: date */
            birthday: string;
            phone_number: string;
            address: string;
            /** Format: date */
            joining_date: string;
            information: string;
        };
        /** @description A simplified representation of a Member, typically used in list views. */
        MemberSummary: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            email: string;
        };
        /** @description Data transfer object for partially updating an existing Member (PATCH operation). */
        MemberPartialUpdate: {
            first_name?: string;
            last_name?: string;
            email?: string;
            /** Format: date */
            birthday?: string;
            phone_number?: string;
            address?: string;
            information?: string;
        };
        /** @description Data transfer object for creating a new Member. */
        MemberCreate: {
            first_name: string;
            last_name: string;
            email: string;
            /** Format: password */
            password: string;
            /** Format: date */
            birthday?: string;
            phone_number?: string;
            address?: string;
            information?: string;
        };
        /** @description Request body for generating a personalized mass-letter PDF for the caller's receivers. */
        PdfRequest: {
            /** @description HTML letter body. Supports per-receiver placeholder tokens (see the operation
             *     description); each token is replaced with that receiver's data. One personalized letter
             *     — a name and address layout block followed by the substituted template — is rendered per
             *     receiver and concatenated into a single PDF.
             *      */
            template: string;
        };
        /** @description Request body for sending a personalized mass email to the caller's receivers. */
        MailRequest: {
            /** @description Subject line of the email. Supports the same per-receiver placeholder tokens as the
             *     template; each token is replaced with that receiver's data before the email is sent.
             *      */
            subject: string;
            /** @description HTML email body. Supports per-receiver placeholder tokens (see the operation
             *     description); each token is replaced with that receiver's data before the email is sent.
             *      */
            template: string;
        };
        /** @description Request body for generating a retrieval-augmented answer. */
        RagRequest: {
            /** @description The question to answer from the PDF knowledge base. */
            question: string;
            /** @description Optional per-request model switch: `true` forces the local Ollama model, `false`
             *     forces OpenAI. When omitted, the service's configured default provider is used.
             *      */
            uselocal?: boolean;
        };
        /** @description Response body containing the generated retrieval-augmented answer. */
        RagResponse: {
            /** @description The generated answer. */
            response: string;
        };
        /** @description The object representation of an Event (e.g., a training session or a match). */
        Event: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            attendees?: components["schemas"]["Reference"][];
            /** @description Sports associated with this event. */
            sports_linked?: components["schemas"]["Reference"][];
            /** @description Teams associated with this event. */
            teams_linked?: components["schemas"]["Reference"][];
            creator: components["schemas"]["Reference"] | null;
        };
        /** @description A simplified representation of a Event, typically used in list views. */
        EventSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            attendees?: components["schemas"]["Reference"][];
        };
        /** @description Data transfer object for partially updating an existing Event (PATCH operation). */
        EventPartialUpdate: {
            name?: string;
            description?: string;
            /** Format: date-time */
            start_time?: string;
            /** Format: date-time */
            end_time?: string;
            attendees?: string[];
            /** @description IDs of the sports associated with this event. */
            sports_linked?: string[];
            teams_linked?: string[];
        };
        /** @description Data transfer object for creating a new Event. */
        EventCreate: {
            name: string;
            description?: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            attendees?: string[];
            /** @description IDs of the sports associated with this event. */
            sports_linked?: string[];
            teams_linked?: string[];
        };
        /** @description The object representation of Feedback, which is associated with a specific Event and Member. */
        Feedback: {
            /** Format: uuid */
            id: string;
            event: components["schemas"]["Reference"];
            member: components["schemas"]["Reference"];
            creator: components["schemas"]["Reference"] | null;
            /** Format: date-time */
            created_at: string;
            feedback: string;
            /** Format: int32 */
            rating: number;
        };
        /** @description A simplified representation of a Feedback, typically used in list views. */
        FeedbackSummary: {
            /** Format: uuid */
            id: string;
            event: components["schemas"]["Reference"];
            member: components["schemas"]["Reference"];
            creator: components["schemas"]["Reference"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            rating: number;
        };
        /** @description Data transfer object for partially updating an existing Feedback (PATCH operation). */
        FeedbackPartialUpdate: {
            event?: string;
            member?: string;
            feedback?: string;
            /** Format: int32 */
            rating?: number;
        };
        /** @description Data transfer object for creating a new Feedback. */
        FeedbackCreate: {
            event: string;
            member: string;
            feedback: string;
            /** Format: int32 */
            rating: number;
        };
        /** @description The object representation of a Transaction, which includes details such as the member, creator, amount, and timestamps. */
        Transaction: {
            /** Format: uuid */
            id: string;
            member: components["schemas"]["Reference"];
            creator: components["schemas"]["Reference"] | null;
            amount_cents: number;
            /** Format: date-time */
            created_at: string;
            title: string;
            description: string;
        };
        /** @description Data transfer object for partially updating an existing Transaction (PATCH operation). */
        TransactionPartialUpdate: {
            member?: string;
            amount_cents?: number;
            title?: string;
            description?: string;
        };
        /** @description Data transfer object for creating a new Transaction. */
        TransactionCreate: {
            member: string;
            amount_cents: number;
            title: string;
            description?: string;
        };
        /** @description The object representation of a Member's Balance, which includes the total balance in cents. */
        Balance: {
            member: components["schemas"]["Reference"];
            balance_cents: number;
        };
    };
    responses: {
        /** @description The server encountered an unexpected condition that prevented it from fulfilling the request. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server cannot find the requested resource. The endpoint may be invalid or the resource may no longer exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server could not understand the request due to invalid syntax. The client should modify the request and try again. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BadRequestResponse"];
            };
        };
        /** @description The request could not be completed due to a conflict with the current state of the resource. Resolve the conflict and try again. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request was successful, but there is no content to return in the response. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Authentication is required to access the requested resource. The client must include the appropriate credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server understood the request, but refuses to authorize it. Ensure the client has appropriate permissions. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        sport_id: string;
        team_id: string;
        member_id: string;
        event_id: string;
        feedback_id: string;
        transaction_id: string;
        report_id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllSports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createSport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new sport. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["SportCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_id: components["parameters"]["sport_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_id: components["parameters"]["sport_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_id: components["parameters"]["sport_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a sport. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["SportPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new team. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a team. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new member. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMemberDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateMemberDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a member. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new event. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getEventDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateEventDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating an event. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating new feedback. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getFeedbackDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateFeedbackDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a specific feedback. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMemberBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new transaction. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a transaction. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    sendMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The subject and HTML template for the personalized mass email. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailRequest"];
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The HTML template for the personalized mass-letter PDF. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PdfRequest"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listMemberReports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberReportSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    generateMemberReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was accepted and report generation has been started. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listTeamReports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamReportSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    generateTeamReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was accepted and report generation has been started. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: components["parameters"]["report_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: components["parameters"]["report_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    generateRagResponse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body containing the question to answer. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagRequest"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the generated answer in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
