/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organization/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all sports
         * @description Returns a list of all sports registered in the organization.
         *     - All authenticated users: can access this endpoint.
         */
        get: operations["getAllSports"];
        put?: never;
        /**
         * Create sport
         * @description Creates a new sport in the organization.
         *     - Admins: can create sports.
         */
        post: operations["createSport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/sports/{sport_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sport
         * @description Returns the details of a specific sport.
         *     - All authenticated users: can access this endpoint.
         */
        get: operations["getSport"];
        put?: never;
        post?: never;
        /**
         * Delete sport
         * @description Deletes a sport from the organization.
         *     - Admins: can delete sports.
         */
        delete: operations["deleteSport"];
        options?: never;
        head?: never;
        /**
         * Update sport
         * @description Partially updates an existing sport's details.
         *     - Directors: can update all fields except directors.
         *     - Admins: can update all fields.
         */
        patch: operations["updateSport"];
        trace?: never;
    };
    "/organization/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all teams
         * @description Returns a list of all teams in the organization.
         *     - All authenticated users: can access this endpoint.
         */
        get: operations["getAllTeams"];
        put?: never;
        /**
         * Create team
         * @description Creates a new team in the organization.
         *     - Directors: can create teams for their own sport.
         *     - Admins: can create teams for any sport.
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get team
         * @description Returns the details of a specific team.
         *     - All authenticated users: can access this endpoint.
         */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        /**
         * Delete team
         * @description Deletes a team from the organization.
         *     - Directors: can delete teams in their sport.
         *     - Admins: can delete any team.
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        /**
         * Update team
         * @description Partially updates a team's details.
         *     - Trainers: can update all fields except sport and trainers.
         *     - Directors: can update all fields except sport.
         *     - Admins: can update all fields.
         */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all members
         * @description Returns a list of all members in the organization.
         *     - All authenticated users: can access this endpoint.
         */
        get: operations["getAllMembers"];
        put?: never;
        /**
         * Create member
         * @description Creates a new member in the organization. Includes a password field for setting initial credentials.
         *     - Admins: can create members.
         */
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get member details
         * @description Returns the full details of a specific member.
         *     - Members themselves: can view their own details.
         *     - Team members: can view details of others in the same team.
         *     - Trainers: can view details of members in their team.
         *     - Directors: can view details of members in their sport.
         *     - Admins: can view any member's details.
         */
        get: operations["getMemberDetails"];
        put?: never;
        post?: never;
        /**
         * Delete member
         * @description Deletes a member from the organization.
         *     - Admins: can delete members.
         */
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        /**
         * Update member details
         * @description Partially updates the details of a specific member.
         *     - Members themselves: can update their own details.
         *     - Admins: can update any member's details.
         */
        patch: operations["updateMemberDetails"];
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all events
         * @description Returns a list of all events.
         *     - All authenticated users: can see events linked to their team or sport, or events where they are an attendee.
         *     - Creators: can see all events they created.
         *     - Admins: can see all events.
         */
        get: operations["getAllEvents"];
        put?: never;
        /**
         * Create event
         * @description Creates a new event.
         *     - Directors: can create events for their sport.
         *     - Trainers: can create events for their team.
         *     - Admins: can create any event.
         */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get event details
         * @description Returns the details of a specific event.
         *     - All authenticated users: can access events linked to their team or sport, or events where they are an attendee.
         *     - Creators: can view events they created.
         *     - Admins: can view any event.
         */
        get: operations["getEventDetails"];
        put?: never;
        post?: never;
        /**
         * Delete event
         * @description Deletes a specific event.
         *     - Creators: can delete events they created.
         *     - Directors: can delete events linked to their sport.
         *     - Admins: can delete any event.
         */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /**
         * Update event details
         * @description Partially updates the details of a specific event.
         *     - Creators: can update events they created.
         *     - Directors: can update events linked to their sport.
         *     - Admins: can update any event.
         */
        patch: operations["updateEventDetails"];
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all feedback
         * @description Returns a list of all feedback entries.
         *     - Creators: can see feedback they submitted.
         *     - Members: can see feedback about themselves.
         *     - Admins: can see all feedback.
         */
        get: operations["getAllFeedback"];
        put?: never;
        /**
         * Create feedback
         * @description Creates a new feedback entry for a member.
         *     - Trainers: can create feedback for their trainees.
         *     - Admins: can create feedback for any member.
         */
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get feedback details
         * @description Returns the details of a specific feedback entry.
         *     - Creators: can view feedback they submitted.
         *     - Members: can view feedback about themselves.
         *     - Admins: can view any feedback.
         */
        get: operations["getFeedbackDetails"];
        put?: never;
        post?: never;
        /**
         * Delete feedback
         * @description Deletes a specific feedback entry.
         *     - Creators: can delete feedback they submitted.
         *     - Admins: can delete any feedback.
         */
        delete: operations["deleteFeedback"];
        options?: never;
        head?: never;
        /**
         * Update feedback details
         * @description Partially updates a specific feedback entry.
         *     - Creators: can update feedback they submitted.
         *     - Admins: can update any feedback.
         */
        patch: operations["updateFeedbackDetails"];
        trace?: never;
    };
    "/finance/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all balances
         * @description Returns a list of all member balances.
         *     - Directors: can view balances of members in their sport.
         *     - Admins: can view all balances.
         */
        get: operations["getAllBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/balances/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get member balance
         * @description Returns the balance of a specific member.
         *     - Members themselves: can view their own balance.
         *     - Directors: can view balances of members in their sport.
         *     - Admins: can view any member's balance.
         */
        get: operations["getMemberBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all transactions
         * @description Returns a list of all transactions. Users only see transactions where they are the member or the creator.
         *     - Members: can see transactions they are part of.
         *     - Creators: can see transactions they created.
         *     - Directors: can see transactions for members in their sport.
         *     - Admins: can see all transactions.
         */
        get: operations["getAllTransactions"];
        put?: never;
        /**
         * Create transaction
         * @description Creates a new financial transaction for a member.
         *     - Directors: can create transactions for members in their sport.
         *     - Admins: can create transactions for any member.
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction
         * @description Returns the details of a specific transaction.
         *     - Members: can view transactions they are part of.
         *     - Creators: can view transactions they created.
         *     - Directors: can view transactions for members in their sport.
         *     - Admins: can view any transaction.
         */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /**
         * Delete transaction
         * @description Deletes a specific transaction.
         *     - Creators: can delete transactions they created.
         *     - Admins: can delete any transaction.
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /**
         * Update transaction
         * @description Partially updates a specific transaction. The member field can only be changed by admins.
         *     - Creators: can update transactions they created (except the member field).
         *     - Admins: can update any transaction including the member field.
         */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/letters/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send mail
         * @description Sends an email based on the provided HTML template.
         *     - Trainers: can send mail to members of their team.
         *     - Directors: can send mail to members related to their sport.
         *     - Admins: can send mail to any member.
         */
        post: operations["sendMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/letters/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get pdf
         * @description Generates and returns a PDF document from the provided HTML template.
         *     - Trainers: can generate PDFs related to their team.
         *     - Directors: can generate PDFs related to their sport.
         *     - Admins: can generate PDFs related to any member.
         */
        post: operations["getPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/helper/report/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate report
         * @description Generates an AI-based report for a member. Members can only generate reports for themselves.
         *     - All authenticated users: can generate a report for themselves.
         *     - Trainers: can generate reports for members of their team.
         *     - Admin: can generate a report for any member.
         */
        get: operations["generateReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            message: string;
        };
        BadRequestResponse: {
            message: string;
            errors?: components["schemas"]["ErrorResponse"][];
        };
        /** @description The object representation of a Sport within the organization. */
        Sport: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date */
            created_at: string;
            directors: string[];
        };
        /** @description Data transfer object for creating a new Sport. */
        SportCreate: {
            name: string;
            description?: string;
            directors?: string[];
        };
        /** @description Data transfer object for partially updating an existing Sport (PATCH operation). */
        SportPartialUpdate: {
            name?: string;
            description?: string;
            directors?: string[];
        };
        /** @description The object representation of a Team that belongs to a specific Sport. */
        Team: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date */
            created_at: string;
            address: string;
            /**
             * Format: uuid
             * @description ID of the sport this team belongs to.
             */
            sport: string;
            trainers: string[];
            trainees: string[];
        };
        /** @description Data transfer object for creating a new Team. */
        TeamCreate: {
            name: string;
            description?: string;
            address?: string;
            /**
             * Format: uuid
             * @description ID of the sport this team belongs to.
             */
            sport: string;
            trainers?: string[];
            trainees?: string[];
        };
        /** @description Data transfer object for partially updating an existing Team (PATCH operation). */
        TeamPartialUpdate: {
            name?: string;
            description?: string;
            address?: string;
            /**
             * Format: uuid
             * @description ID of the sport this team belongs to.
             */
            sport?: string;
            trainers?: string[];
            trainees?: string[];
        };
        /** @description The object representation of a Member. All users are represented as a member. */
        Member: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            email: string;
            /** Format: date */
            birthday: string;
            phone_number: string;
            address: string;
            /** Format: date */
            joining_date: string;
            information: string;
        };
        /** @description A simplified representation of a Member, typically used in list views. */
        MemberSummary: {
            /** Format: uuid */
            id: string;
            first_name: string;
            last_name: string;
            email: string;
        };
        /** @description Data transfer object for partially updating an existing Member (PATCH operation). */
        MemberPartialUpdate: {
            first_name?: string;
            last_name?: string;
            email?: string;
            /** Format: date */
            birthday?: string;
            phone_number?: string;
            address?: string;
            information?: string;
        };
        /** @description Data transfer object for creating a new Member. */
        MemberCreate: {
            first_name: string;
            last_name: string;
            email: string;
            /** Format: password */
            password: string;
            /** Format: date */
            birthday?: string;
            phone_number?: string;
            address?: string;
            information?: string;
        };
        /** @description The object representation of an Event (e.g., a training session or a match). */
        Event: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            attendees?: string[];
            /** @description IDs of the sports associated with this event. */
            sports_linked?: string[];
            /** @description IDs of the teams associated with this event. */
            teams_linked?: string[];
            creator: string;
        };
        /** @description A simplified representation of a Event, typically used in list views. */
        EventSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
        };
        /** @description Data transfer object for partially updating an existing Event (PATCH operation). */
        EventPartialUpdate: {
            name?: string;
            description?: string;
            /** Format: date-time */
            start_time?: string;
            /** Format: date-time */
            end_time?: string;
            attendees?: string[];
            /** @description IDs of the sports associated with this event. */
            sports_linked?: string[];
            teams_linked?: string[];
        };
        /** @description Data transfer object for creating a new Event. */
        EventCreate: {
            name: string;
            description?: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            attendees?: string[];
            /** @description IDs of the sports associated with this event. */
            sports_linked?: string[];
            teams_linked?: string[];
        };
        /** @description The object representation of Feedback, which is associated with a specific Event and Member. */
        Feedback: {
            /** Format: uuid */
            id: string;
            event: string;
            member: string;
            creator: string;
            /** Format: date-time */
            created_at: string;
            feedback: string;
        };
        /** @description A simplified representation of a Feedback, typically used in list views. */
        FeedbackSummary: {
            /** Format: uuid */
            id: string;
            event: string;
            member: string;
            creator: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Data transfer object for partially updating an existing Feedback (PATCH operation). */
        FeedbackPartialUpdate: {
            event?: string;
            member?: string;
            feedback?: string;
        };
        /** @description Data transfer object for creating a new Feedback. */
        FeedbackCreate: {
            event: string;
            member: string;
            feedback: string;
        };
        /** @description The object representation of a Transaction, which includes details such as the member, creator, amount, and timestamps. */
        Transaction: {
            /** Format: uuid */
            id: string;
            member: string;
            creator: string;
            amount_cents: number;
            /** Format: date-time */
            created_at: string;
            title: string;
            description: string;
        };
        /** @description Data transfer object for partially updating an existing Transaction (PATCH operation). */
        TransactionPartialUpdate: {
            member?: string;
            amount_cents?: number;
            title?: string;
            description?: string;
        };
        /** @description Data transfer object for creating a new Transaction. */
        TransactionCreate: {
            member: string;
            amount_cents: number;
            title: string;
            description?: string;
        };
        /** @description The object representation of a Member's Balance, which includes the total balance in cents. */
        Balance: {
            member: string;
            balance_cents: number;
        };
    };
    responses: {
        /** @description The server encountered an unexpected condition that prevented it from fulfilling the request. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server cannot find the requested resource. The endpoint may be invalid or the resource may no longer exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server could not understand the request due to invalid syntax. The client should modify the request and try again. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BadRequestResponse"];
            };
        };
        /** @description The request could not be completed due to a conflict with the current state of the resource. Resolve the conflict and try again. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request was successful, but there is no content to return in the response. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Authentication is required to access the requested resource. The client must include the appropriate credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The server understood the request, but refuses to authorize it. Ensure the client has appropriate permissions. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        sport_id: string;
        team_id: string;
        member_id: string;
        event_id: string;
        feedback_id: string;
        transaction_id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllSports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createSport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new sport. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["SportCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_id: components["parameters"]["sport_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_id: components["parameters"]["sport_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sport_id: components["parameters"]["sport_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a sport. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["SportPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new team. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: components["parameters"]["team_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a team. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new member. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMemberDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateMemberDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a member. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new event. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getEventDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateEventDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["event_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating an event. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating new feedback. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getFeedbackDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateFeedbackDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: components["parameters"]["feedback_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a specific feedback. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMemberBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Balance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAllTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for creating a new transaction. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description The request was successful, and a new resource was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, but there is no content to return in the response. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: components["parameters"]["transaction_id"];
            };
            cookie?: never;
        };
        /** @description The request body for partially updating a transaction. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPartialUpdate"];
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    sendMail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for sending mail. It will be used in the email content. It must be a valid HTML string using the template format with placeholders for dynamic content. */
        requestBody: {
            content: {
                "text/html": string;
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getPdf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for generating a pdf from a template. It must be a valid HTML string using the template format with placeholders for dynamic content. */
        requestBody: {
            content: {
                "text/html": string;
            };
        };
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    generateReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: components["parameters"]["member_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request was successful, and the server has returned the requested resource in the response body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
