spring.application.name=letter-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/auth/realms/devops
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/devops/protocol/openid-connect/certs
