{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  labels:
    {{- include "team-devoops.labels" (dict "name" "keycloak-credentials" "root" $) | nindent 4 }}
type: Opaque
stringData:
  KC_DB_PASSWORD: {{ .Values.keycloak.db.password | quote }}
  POSTGRES_PASSWORD: {{ .Values.keycloak.db.password | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
{{- end }}
