{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  labels:
    {{- include "team-devoops.labels" (dict "name" "ollama" "root" $) | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ollama.storageSize }}
{{- end }}
